/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'

/* Instruments */
import { fetchPlayerHistoryAsync } from './thunks'
import { PlayerHistory } from '@/types/PlayerHistory'

const initialState: PlayerHistorySliceState = {
  playerHistorys: new Array(774),
  status: 'idle',
}

export const playerHistorySlice = createSlice({
  name: 'playerHistory',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1
    // },
    // decrement: (state) => {
    //   state.value -= 1
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchPlayerHistoryAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(fetchPlayerHistoryAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        if(action.payload){
          state.playerHistorys[action.payload[0].element] = action.payload
        }
      })
  },
})

/* Types */
export interface PlayerHistorySliceState {
  playerHistorys: PlayerHistory[][],
  status: 'idle' | 'loading' | 'failed'
}
